### ISSUE TITLE
Add instructions on how to use repo

### ISSUE THREAD

**Issue by prashantchaudhary1** [replicate/flux-fine-tuner#36]
The Readme file is missing instructions on how to use repo to fine tune a Flux.1 model on self/custom images. Please add the instructions or a link to how to guide.

**Comment by fofr** [comment]
Do the linked to guides work for you?
https://github.com/replicate/flux-fine-tuner?tab=readme-ov-file#getting-started

Or did you want to run this on your own local/cloud GPU?

**Comment by Zeeshanzt** [comment]
Instructions related to running it local or cloud would be great @fofr . there are dependencies issues of pydantic, cog etc.

**Comment by prashantchaudhary1** [comment]
I am trying to run it on moderately priced cloud GPU with 24GB RAM (though RAM may be increased if required)

**Comment by lucataco** [comment]
To learn more about Cog and how to train with it, see our [Cog documentation here](https://github.com/replicate/cog/blob/main/docs/training.md)
