### ISSUE TITLE
Training on object & style

### ISSUE THREAD

**Issue by tomtev** [replicate/flux-fine-tuner#37]
Is it possible to train on an object AND style in the same training?

**Comment by fofr** [comment]
Yes, but you might not be able to separate the two during inference later.

**Comment by NickCoronges-RGA** [comment]
On this topic, in terms of configuration for training for an object vs a style, i see people recommend lowering lora_lr and increasing steps but are there other levers to consider (beyond the training data)?

**Comment by lucataco** [comment]
Check the [Readme](https://replicate.com/ostris/flux-dev-lora-trainer/readme) for object vs style
