### ISSUE TITLE
Where's openai/clip-vit-large-patch14-336 used for in caption.py?

### ISSUE THREAD

**Issue by jonbesga** [replicate/flux-fine-tuner#40]
Many thanks for making this code open source!

I noticed in caption.py the model `openai/clip-vit-large-patch14-336` is downloaded but can't figure out where it seems to be used?

**Comment by lucataco** [comment]
Its used in the [captioner](https://github.com/replicate/flux-fine-tuner/blob/9359a41c73246a4fcc55a4f99b6b1bab97641cb1/caption.py#L43C18-L43C51)

**Comment by lucataco** [comment]
Its used by Llava to caption the images
