### ISSUE TITLE
Error when training the model on replicate

### ISSUE THREAD

**Issue by mufayed** [replicate/flux-fine-tuner#47]
I'm trying to train the model at replicate but I'm getting that error
https://replicate.com/ostris/flux-dev-lora-trainer/train

`Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.15/lib/python3.10/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
File "/src/train.py", line 207, in train
clean_up()
File "/src/train.py", line 478, in clean_up
shutil.rmtree(WEIGHTS_PATH)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/shutil.py", line 725, in rmtree
_rmtree_safe_fd(fd, path, onerror)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
_rmtree_safe_fd(dirfd, fullname, onerror)
File "/root/.pyenv/versions/3.10.15/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
onerror(os.unlink, fullname, sys.exc_info())
File "/root/.pyenv/versions/3.10.15/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 30] Read-only file system: 'vocab.json'`

**Comment by aiheadshots** [comment]
yes, same happening when I'm fine tuning on replicate platform. Some bugs in their pipeline I guess

**Comment by aiheadshots** [comment]
@fofr @andreasjansson @zeke @lucataco @daanelson @zsxkib @erbridge @bfirsh @mattt @jakedahn @evazorro please review this major bug. No training is being initiated on replicate

**Comment by digitaljohn** [comment]
Adding my voice. Exact same issue here.

**Comment by andreasjansson** [comment]
Thank you for the reports, we are investigating this and will reply here once it has been resolved.

**Comment by andreasjansson** [comment]
This has been resolved now. Feel free to re-open this issue if it happens again. We are also tightening up our alerts so we catch this class of errors sooner in the future.

I'm sorry for the trouble that this caused.

**Comment by digitaljohn** [comment]
Tested and confirmed resolved, thanks for the super quick response!

**Comment by mufayed** [comment]
Tested, it's working now, Thanks for your dedicated support.

**Comment by moogleLabsDev** [comment]
Again this issue popped up for the latest and previous versions

**Comment by andreasjansson** [comment]
@moogleLabsDev are you getting the `Read-only file system: 'vocab.json'` error? I'm not able to reproduce that. Are you creating the training through web or API? If API, could you share the API call? Feel free to email to andreas@replicate.com if it's secret.

**Comment by andreasjansson** [comment]
I'm seeing slow uploads to Google Cloud Storage at the moment when creating the training through web. In the UI, the Create training button is spinning for a long time (up to several minutes). Is that what you're seeing too @moogleLabsDev ?

**Comment by moogleLabsDev** [comment]
it's fine now
