### ISSUE TITLE
New version is not working

### ISSUE THREAD

**Issue by neuralclient** [replicate/flux-fine-tuner#48]
Hi new version is not working as its stucks on starting status and training is not starting

**Comment by DazzlerLabs** [comment]
Hi! Same for me, already waiting a couple of hours. Please revert it back.  @andreasjansson

**Comment by neuralclient** [comment]
Yes and there is no option to run old version, please fix the issues @andreasjansson

**Comment by andreasjansson** [comment]
Thank you for the messages, we are actively investigating this.

**Comment by andreasjansson** [comment]
We have finally found the root cause and resolved this issue. It will still be a couple of minutes before the queues are clear and trainings start being scheduled.

I am sorry for the impact this has caused on your products. We are working hard to improve the reliability of our training system.

**Comment by neuralclient** [comment]
No issue, by the way nice model really love it and love to contribute to it.
