### ISSUE TITLE
Custom width/height capped to 1440 whereas 21:9 aspect ratio goes up to 1536

### ISSUE THREAD

**Issue by simonpicard** [replicate/flux-fine-tuner#55]
Hi,

For image generation, when setting custom width or height, the maximal value is 1440.
However, when using the aspect ratio, it is possible to reach 1536 using 21:9.
the limitation should be consistent and the maximal allowed value for width and height should be 1536.

Many thanks.

**Comment by lucataco** [comment]
Flux can handle images up to 2MP. We chose 1440 as the default maximum for individual dimensions as a practical limit that works well for most use cases while staying within the constraint
