### ISSUE TITLE
Status on trained model

### ISSUE THREAD

**Issue by KrinsKumar** [replicate/flux-fine-tuner#57]
I am using a pipeline to train a model. Is there a route or a hook I can use to get the status of the model training. Status as in "Training || Queued || Completed || Failed" or something?

**Comment by lucataco** [comment]
Training status can be starting/succeeded/etc
For more info see our docs here: [https://github.com/replicate/replicate-javascript/blob/main/README.md](https://github.com/replicate/replicate-javascript/blob/main/README.md)
